#!/bin/bash

# The list of stacksets to update
stacksets=(
    "roles"
    "secrets"
    "s3-log"
    "config"
    "cloud-watch"
    "backup"
    "ec2patching"
    "rds-parameter-groups"
)

# Get the directory where "update-stack-all" lives. May not necessarily be `pwd`
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

for stackset in "${stacksets[@]}"; do
    echo Adding ised-"${stackset}"
    "${DIR}"/update-stack "${stackset}"
done
