#!/bin/bash
# ./update-stack secret

#aws cloudformation update-stack-set --stack-set-name ised-$1 --template-url https://ised-s3-256255698049-cf.s3.ca-central-1.amazonaws.com/cf-stacks/$1.yaml --parameters file://./../cf-parameters/$1.json --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --accounts file://./../scripts/accounts.json --regions ca-central-1
aws cloudformation update-stack-set --stack-set-name ised-$1 --template-url https://ised-s3-256255698049-cf.s3.ca-central-1.amazonaws.com/cf-stacks/$1.yaml --parameters file://./../cf-parameters/$1.json --accounts file://./../scripts/accounts.json --regions ca-central-1
