#!/bin/bash
# ./update-stack secret

aws cloudformation update-stack-set --stack-set-name ised-secrets --template-url https://ised-s3-256255698049-cf.s3.ca-central-1.amazonaws.com/cf-stacks/secrets.yaml --parameters file://./../cf-parameters/secrets.json --accounts file://./../scripts/accounts.json --regions ca-central-1
aws cloudformation update-stack-set --stack-set-name ised-s3-log --template-url https://ised-s3-256255698049-cf.s3.ca-central-1.amazonaws.com/cf-stacks/s3-log.yaml --parameters file://./../cf-parameters/s3-log.json --accounts file://./../scripts/accounts.json --regions ca-central-1
aws cloudformation update-stack-set --stack-set-name ised-roles --template-url https://ised-s3-256255698049-cf.s3.ca-central-1.amazonaws.com/cf-stacks/roles.yaml --parameters file://./../cf-parameters/roles.json --accounts file://./../scripts/accounts.json --regions ca-central-1
